app:
  build: .
  links:
    - redis
    - postgres
  volumes:
    - .:/var/www
  volumes_from:
    - data
  tty: true

data:
  build: dockerdev/data/

nginx:
  build: dockerdev/nginx/
  ports:
    - 8081:80
  links:
    - fpm
  volumes_from:
    - app
  environment:
    <APP_SERVER_NAME>: dev-machine

fpm:
  build: dockerdev/php-fpm/
  links:
    - redis
    - postgres
  volumes_from:
    - app
  environment:
    APP_SERVER_NAME: dev-machine

redis:
  image: redis:2.8.13

postgres:
  image: postgres
  ports:
      - "5434:5432"
  environment:
    POSTGRES_PASSWORD: "pass"