services:
    doctrine_event_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory_service: doctrine # this is an instance of Registry
        factory_method: getRepository
        arguments: [ "Meetupos\\Domain\\Model\\Event\\Event" ]