fos_rest:
    disable_csrf_role: ROLE_API
    routing_loader:
        default_format: json
        include_format: false
    view:
        formats:
            json: true
            xml:  true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }