meetupos_auth_api:
    resource: "@MeetuposAuthApiBundle/Resources/config/routing.yml"
    prefix:   /

meetupos_api:
    resource: "@MeetuposApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
