real_funding_api_homepage:
    path:     /hello/{name}
    defaults: { _controller: MeetuposApiBundle:User:index }

event:
    path: /events
    defaults: { _controller: sf_event_controller:postEvent }
#    defaults: { _controller: MeetuposApiBundle:Event:postEvent }
