real_funding_api_homepage:
    path:     /hello/{name}
    defaults: { _controller: MeetuposApiBundle:User:index }

post_event:
    path: /events
    defaults: { _controller: sf_event_controller:postEvent }
    methods:  [POST]

get_event:
    path: /events/{id}
    defaults: { _controller: sf_event_controller:getEvent }
    methods:  [GET]

delete_event:
    path: /events/{id}
    defaults: { _controller: sf_event_controller:deleteEvent }
    methods:  [DELETE]